# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('FirstName', models.CharField(blank=True, max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=500)),
                ('Telephone', models.CharField(blank=True, max_length=20)),
                ('DateJoined', models.DateTimeField(blank=True, verbose_name='RegisterDate')),
            ],
        ),
    ]
