# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160630_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
