# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Image',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
