# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articlematch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_News', models.IntegerField()),
                ('Weight', models.FloatField(max_length=100)),
                ('News', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='articlematch',
            unique_together=set([('News', 'Match_News')]),
        ),
    ]
