# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articlematch', '0002_auto_20160717_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlematch',
            name='Match_News',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articlematch',
            name='News',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
