# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlematch', '0003_auto_20160717_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlematch',
            name='Content_similarity',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articlematch',
            name='Name_similarity',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articlematch',
            name='User_feedback',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
