# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlematch', '0005_auto_20160801_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlematch',
            name='User_feedback',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
    ]
